### ISSUE TITLE
Update bazel module versions

### ISSUE THREAD

**Issue by lukaszwawrzyk** [VirtusLab/bazel-steward#67]
New way of managing dependencies on rules (replacement for #66). See: https://bazel.build/build/bzlmod
It is not yet widely adapted, it is a new feature of bazel, but it will be more widely used eventually.

**Comment by evis** [comment]
Are there any plans for this issue?

Bzlmod is enabled by default from 7.0.0: https://github.com/bazelbuild/bazel/releases/tag/7.0.0

**Comment by kaspar4** [comment]
FWIW, bazel gives easy access to versions
```
bazel mod graph                                               
<root> (@_)
├───aspect_bazel_lib@2.0.1 
│   ├───bazel_skylib@1.5.0 (*) 
│   ├───platforms@0.0.7 
│   │   └───rules_license@0.0.7 (*) 
│   └───stardoc@0.5.4 
│       ├───bazel_skylib@1.5.0 (*) 
│       ├───rules_license@0.0.7 (*) 
│       └───rules_java@7.1.0 
│           ├───bazel_skylib@1.5.0 (*) 
│           ├───platforms@0.0.7 (*) 
│           ├───rules_cc@0.0.9 (*) 
│           ├───rules_license@0.0.7 (*) 
│           └───rules_proto@4.0.0 (*) 
├───bazel_skylib@1.5.0 
│   └───platforms@0.0.7 (*) 
├───buildifier_prebuilt@6.3.3 
│   ├───bazel_skylib@1.5.0 (*) 
│   └───platforms@0.0.7 (*) 
├───gazelle@0.34.0 
│   ├───bazel_skylib@1.5.0 (*) 
│   ├───rules_go@0.43.0 (*) 
│   ├───protobuf@3.19.6 
│   │   ├───bazel_skylib@1.5.0 (*) 
│   │   ├───rules_cc@0.0.9 (*) 
│   │   ├───rules_java@7.1.0 (*) 
│   │   ├───rules_proto@4.0.0 (*) 
│   │   ├───rules_python@0.10.2 (*) 
│   │   └───zlib@1.3 
│   │       ├───platforms@0.0.7 (*) 
│   │       └───rules_cc@0.0.9 (*) 
│   └───rules_proto@4.0.0 
│       ├───bazel_skylib@1.5.0 (*) 
│       └───rules_cc@0.0.9 (*) 
├───hermetic_cc_toolchain@2.1.3 
│   └───platforms@0.0.7 (*) 
├───llvm-project@17.0.3 
│   ├───bazel_skylib@1.5.0 (*) 
│   ├───platforms@0.0.7 (*) 
│   └───rules_cc@0.0.9 
│       └───platforms@0.0.7 (*) 
├───rules_distroless@0.1.2 
│   ├───aspect_bazel_lib@2.0.1 (*) 
│   └───bazel_skylib@1.5.0 (*) 
├───rules_go@0.43.0 
│   ├───bazel_skylib@1.5.0 (*) 
│   ├───gazelle@0.34.0 (*) 
│   ├───platforms@0.0.7 (*) 
│   ├───protobuf@3.19.6 (*) 
│   ├───rules_proto@4.0.0 (*) 
│   └───bazel_features@1.1.1 
├───rules_oci@1.4.3 
│   ├───aspect_bazel_lib@2.0.1 (*) 
│   ├───bazel_skylib@1.5.0 (*) 
│   └───platforms@0.0.7 (*) 
└───rules_pkg@0.9.1 
    ├───bazel_skylib@1.5.0 (*) 
    ├───rules_license@0.0.7 
    └───rules_python@0.10.2 

```

and buildozer might (haven't checked or played with this) be able to edit MODULE.bazel cleanly.

**Comment by hb-man** [comment]
+1 to this issue, we also suddenly realized steward stoped working with migration to bzlmod.
with some reconfiguring of `search-paths` I was able to make it look up and update maven dependencies, but mechanism for obtaining rules in repo broke down completely and doesn't update them anymore (because it can't discover them).

**Comment by lukaszwawrzyk** [comment]
@hb-man would you mind sharing your updated config for maven?
You are correct that steward now works for updating bazel and maven, but not for the bzlmod.
I hope to find some time to implement it this year :D

**Comment by hb-man** [comment]
@lukaszwawrzyk oh, it was easy - I didn't get into why exactly the maven deps discovery mechanism still worked, but it did, so I just added the path to `MODULE.bzlmod` file to config for updates, since at least steward is agnostic to where dependencies are declared. [This is our config.](https://github.com/JetBrains/bazel-bsp/blob/master/bazel-steward.yaml)

But with rules discovery it uses `WORKSPACE` file with no way to configure, and since most deps are moved to `MODULE.bzlmod` it stoped working completely.
